sonar.projectKey=MyProject
sonar.sources=src/
sonar.host.url=http://localhost:9000
sonar.login=sqp_8342c913e07a308b6e6c2ac9ebf0baf271364422
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
